import json
import os


air_terminals_supply_settings = [["0001-0252", ("DQJ-Q-SR-Z-310", "35dB", "air supply - Rotational", "Nawiewnik wirowy prostokatny z izolowana skrzynka rozprezna, bez przepustnicy, z kroccem okragłym DQJA-SR-310 ф160.")],
                              ["0253-0297", ("DQJ-Q-SR-Z-400", "35dB", "air supply - Rotational",
                                             "Nawiewnik wirowy prostokatny z izolowana skrzynka rozprezna, bez przepustnicy, z kroccem okragłym DQJA-SR-400 ф160.")],
                              ["0298-0501", ("DQJ-Q-SR-Z-500", "35dB", "air supply - Rotational",
                                             "Nawiewnik wirowy prostokatny z izolowana skrzynka rozprezna, bez przepustnicy, z kroccem okragłym DQJA-SR-500 ф200.")],
                              ["0502-0754", ("DQJ-Q-SR-Z-600", "35dB", "air supply - Rotational",
                                             "Nawiewnik wirowy prostokatny z izolowana skrzynka rozprezna, bez przepustnicy, z kroccem okragłym DQJA-SR-600 ф250.")],
                              ["0755-1115", ("DQJ-Q-SR-Z-800", "35dB", "air supply - Rotational",
                                             "Nawiewnik wirowy prostokatny z izolowana skrzynka rozprezna, bez przepustnicy, z kroccem okragłym DQJA-SR-800 ф350.")],
                              ["0001-0210", ("DQJ-Q-SR-Z-310", "30dB", "air supply - Rotational",
                                             "Nawiewnik wirowy prostokatny z izolowana skrzynka rozprezna, bez przepustnicy, z kroccem okragłym DQJA-SR-310 ф160.")],
                              ["0211-0245", ("DQJ-Q-SR-Z-400", "30dB", "air supply - Rotational",
                                             "Nawiewnik wirowy prostokatny z izolowana skrzynka rozprezna, bez przepustnicy, z kroccem okragłym DQJA-SR-400 ф160.")],
                              ["0246-0412", ("DQJ-Q-SR-Z-500", "30dB", "air supply - Rotational",
                                             "Nawiewnik wirowy prostokatny z izolowana skrzynka rozprezna, bez przepustnicy, z kroccem okragłym DQJA-SR-500 ф200.")],
                              ["0413-0621", ("DQJ-Q-SR-Z-600", "30dB", "air supply - Rotational",
                                             "Nawiewnik wirowy prostokatny z izolowana skrzynka rozprezna, bez przepustnicy, z kroccem okragłym DQJA-SR-600 ф250.")],
                              ["0622-0919", ("DQJ-Q-SR-Z-800", "30dB", "air supply - Rotational",
                                             "Nawiewnik wirowy prostokatny z izolowana skrzynka rozprezna, bez przepustnicy, z kroccem okragłym DQJA-SR-800 ф350.")],
                              ["0001-0173", ("DQJ-Q-SR-Z-310", "25dB", "air supply - Rotational",
                                             "Nawiewnik wirowy prostokatny z izolowana skrzynka rozprezna, bez przepustnicy, z kroccem okragłym DQJA-SR-310 ф160.")],
                              ["0177-0202", ("DQJ-Q-SR-Z-400", "25dB", "air supply - Rotational",
                                             "Nawiewnik wirowy prostokatny z izolowana skrzynka rozprezna, bez przepustnicy, z kroccem okragłym DQJA-SR-400 ф160.")],
                              ["0203-0340", ("DQJ-Q-SR-Z-500", "25dB", "air supply - Rotational",
                                             "Nawiewnik wirowy prostokatny z izolowana skrzynka rozprezna, bez przepustnicy, z kroccem okragłym DQJA-SR-500 ф200.")],
                              ["0341-0512", ("DQJ-Q-SR-Z-600", "25dB", "air supply - Rotational",
                                             "Nawiewnik wirowy prostokatny z izolowana skrzynka rozprezna, bez przepustnicy, z kroccem okragłym DQJA-SR-600 ф250.")],
                              ["0513-0758", ("DQJ-Q-SR-Z-800", "25dB", "air supply - Rotational",
                                             "Nawiewnik wirowy prostokatny z izolowana skrzynka rozprezna, bez przepustnicy, z kroccem okragłym DQJA-SR-800 ф350.")],
                              ["0001-0274", ("DQJ-Q-SQ-Z-310", "35dB", "air supply - Rotational",
                                             "Nawiewnik wirowy prostokatny z izolowana skrzynka rozprezna, bez przepustnicy, z kroccem okragłym DQJA-SR-310 ф160.")],
                              ["0275-0327", ("DQJ-Q-SQ-Z-400", "35dB", "air supply - Rotational",
                                             "Nawiewnik wirowy prostokatny z izolowana skrzynka rozprezna, bez przepustnicy, z kroccem okragłym DQJA-SR-400 ф160.")],
                              ["0328-0593", ("DQJ-Q-SQ-Z-500", "35dB", "air supply - Rotational",
                                             "Nawiewnik wirowy prostokatny z izolowana skrzynka rozprezna, bez przepustnicy, z kroccem okragłym DQJA-SR-500 ф200.")],
                              ["0594-0833", ("DQJ-Q-SQ-Z-600", "35dB", "air supply - Rotational",
                                             "Nawiewnik wirowy prostokatny z izolowana skrzynka rozprezna, bez przepustnicy, z kroccem okragłym DQJA-SR-600 ф250.")],
                              ["0834-1345", ("DQJ-Q-SQ-Z-800", "35dB", "air supply - Rotational",
                                             "Nawiewnik wirowy prostokatny z izolowana skrzynka rozprezna, bez przepustnicy, z kroccem okragłym DQJA-SR-800 ф350.")],
                              ["0001-0227", ("DQJ-Q-SQ-Z-310", "30dB", "air supply - Rotational",
                                             "Nawiewnik wirowy prostokatny z izolowana skrzynka rozprezna, bez przepustnicy, z kroccem okragłym DQJA-SR-310 ф160.")],
                              ["0228-0269", ("DQJ-Q-SQ-Z-400", "30dB", "air supply - Rotational",
                                             "Nawiewnik wirowy prostokatny z izolowana skrzynka rozprezna, bez przepustnicy, z kroccem okragłym DQJA-SR-400 ф160.")],
                              ["0270-0495", ("DQJ-Q-SQ-Z-500", "30dB", "air supply - Rotational",
                                             "Nawiewnik wirowy prostokatny z izolowana skrzynka rozprezna, bez przepustnicy, z kroccem okragłym DQJA-SR-500 ф200.")],
                              ["0496-0685", ("DQJ-Q-SQ-Z-600", "30dB", "air supply - Rotational",
                                             "Nawiewnik wirowy prostokatny z izolowana skrzynka rozprezna, bez przepustnicy, z kroccem okragłym DQJA-SR-600 ф250.")],
                              ["0686-1106", ("DQJ-Q-SQ-Z-800", "30dB", "air supply - Rotational",
                                             "Nawiewnik wirowy prostokatny z izolowana skrzynka rozprezna, bez przepustnicy, z kroccem okragłym DQJA-SR-800 ф350.")],
                              ["0001-0188", ("DQJ-Q-SQ-Z-310", "25dB", "air supply - Rotational",
                                             "Nawiewnik wirowy prostokatny z izolowana skrzynka rozprezna, bez przepustnicy, z kroccem okragłym DQJA-SR-310 ф160.")],
                              ["0189-0222", ("DQJ-Q-SQ-Z-400", "25dB", "air supply - Rotational",
                                             "Nawiewnik wirowy prostokatny z izolowana skrzynka rozprezna, bez przepustnicy, z kroccem okragłym DQJA-SR-400 ф160.")],
                              ["0223-0414", ("DQJ-Q-SQ-Z-500", "25dB", "air supply - Rotational",
                                             "Nawiewnik wirowy prostokatny z izolowana skrzynka rozprezna, bez przepustnicy, z kroccem okragłym DQJA-SR-500 ф200.")],
                              ["0415-0563", ("DQJ-Q-SQ-Z-600", "25dB", "air supply - Rotational",
                                             "Nawiewnik wirowy prostokatny z izolowana skrzynka rozprezna, bez przepustnicy, z kroccem okragłym DQJA-SR-600 ф250.")],
                              ["0564-0909", ("DQJ-Q-SQ-Z-800", "25dB", "air supply - Rotational",
                                             "Nawiewnik wirowy prostokatny z izolowana skrzynka rozprezna, bez przepustnicy, z kroccem okragłym DQJA-SR-800 ф350.")],
                              ]
json_object = json.dumps(air_terminals_supply_settings, indent=1)
print(json_object)

with open("PYLAB.extension\PYLAB.tab\DuringTests.Panel\Air_terminal_calc.pushbutton\\air_terminals_supply_settings.json", "w") as outfile:
    json.dump(air_terminals_supply_settings, outfile, indent=1)
